#ifndef LINUX_SESSION_H
#define LINUX_SESSION_H

#include <netinet/in.h>
#include <string>
#include <memory>
#include <functional>
#include <thread>
#include <sys/socket.h>
#include <unistd.h>
#include <errno.h>
#include <iostream>
#include <arpa/inet.h>
#include <cstring>
#include <atomic>

#include "aligned_buffer.h"

#define __SOCKET_TIMEOUT_MAXIMUM_ITERATION_COUNT__   20
#define __SOCKET_RECEIVE_BUFFER_SIZE_BYTES__         1024UL
#define __SOCKET_SEND_PACKAGE_SIZE_BYTES__           1024UL

namespace vuprs
{
    struct SocketReceiveData
    {
        char buf[__SOCKET_RECEIVE_BUFFER_SIZE_BYTES__];  /* reserve buffer */
        ssize_t receiveBytes;  /* received bytes, 0: receive none, >0 receive bytes */
        bool is_connect;  /* true: client is connect, false: client is disconnect */
        bool is_timeout;  /* true: timeout, false: no timeout */
        bool is_error;  /* true: error occurred, false: no error */
    };

    void SetSocketReceiveDataToDefault(vuprs::SocketReceiveData *data);

    /**
     * @brief use: void(int client_fd, const struct sockaddr_in& client_addr, const std::string& message)
     * 
     * @param client_fd file descripter of client.
     * @param client_addr client information struct.
     * @param message message(command) to deal with.
     */
    using SessionMessageHandler = std::function<void(int client_fd, const struct sockaddr_in& client_addr, const std::string& message)>;

    class LinuxSession 
    {
        private:
        
            std::atomic<int> client_fd;
            struct sockaddr_in client_addr;
            std::atomic<bool> running;

            std::string frameHeader, frameTailer;  /* Frame Header & Tailer */

            vuprs::SessionMessageHandler messageHandler;

            void ReceiveLoop();

            std::string DefaultMessageProcess(const std::string& message);

        public:

            /** 
             * @brief Generated by accept()
             */
            LinuxSession(int client_fd, const struct sockaddr_in& client_addr, const std::string &frameHeader, const std::string &frameTailer);
            ~LinuxSession();

            /* Disable copy */

            LinuxSession(const LinuxSession&) = delete;
            LinuxSession& operator=(const LinuxSession&) = delete;

            LinuxSession(LinuxSession&& other) = delete;
            LinuxSession& operator=(LinuxSession&& other) = delete;

            /**
             * @brief Start receive loop.
             */
            void Start();

            /**
             * @brief Close client file descriptor and stop running.
             */
            void Stop();

            /**
             * @brief Send string message to client
             */
            bool SendData(const std::string &message);

            /**
             * @brief Receive loop is running.
             */
            bool IsRun() const;

            /**
             * @brief Get client information.
             * @retval {ip}:{port}
             */
            std::string GetClientInfo() const;

            /**
             * @brief Define message handler operate function.
             * @note  Perform the main operation in this function (FPGA control & Fault processing).
             * @param handler call back function pointer.
             */
            void SetMessageHandler(vuprs::SessionMessageHandler handler);
    };

    bool SocketSendData(int client_fd, const char *buf, const uint64_t &sendLength, ssize_t *origin_ret, uint64_t *sendBytes);

    /**
     * @brief Socket receive command.
     * 
     * @param client_fd client file descriptor.
     * @param tailer frame tailer.
     * @param data output data.
     */
    void SocketReceiveCommand(int client_fd, const std::string &tailer, vuprs::SocketReceiveData *data);

    bool SocketSendFile(int client_fd, const std::string &filename);

    /**
     * @brief Send buffer to socket.
     * 
     * @param client_fd client fd.
     * @param buffer aligned DMA buffer.
     */
    bool SocketSendBuffer(int client_fd, const vuprs::AlignedBufferDMA &buffer);

    bool ParseMessageFromSocketData(const vuprs::SocketReceiveData &data, const std::string &header, const std::string &tailer, std::string *result);
}

#endif
