#ifndef TCP_SESSION_H
#define TCP_SESSION_H

#include <netinet/in.h>
#include <string>
#include <memory>
#include <functional>
#include <thread>
#include <sys/socket.h>
#include <unistd.h>
#include <errno.h>
#include <iostream>
#include <arpa/inet.h>
#include <cstring>

#include "nerwork_exception.h"

#define __SOCKET_TIMEOUT_MAXIMUM_ITERATION_COUNT__   20
#define __SOCKET_RECEIVE_BUFFER_SIZE_BYTES__         1024UL

namespace vuprs
{
    /**
     * @brief use: void(int client_fd, const struct sockaddr_in& client_addr, const std::string& message)
     */
    using SessionMessageHandler = std::function<void(int client_fd, const struct sockaddr_in& client_addr, const std::string& message)>;

    class TcpSession {
        public:

            /** 
             * @brief Generated by accept()
             */
            TcpSession(int client_fd, const struct sockaddr_in& client_addr);
            ~TcpSession();

            /* Disable copy */

            TcpSession(const TcpSession&) = delete;
            TcpSession& operator=(const TcpSession&) = delete;

            TcpSession(TcpSession&& other) noexcept;
            TcpSession& operator=(TcpSession&& other) noexcept;

            /**
             * @brief Start receive loop.
             */
            void start();

            /**
             * @brief Close client file descriptor and stop running.
             */
            void stop();

            /**
             * @brief Send string message to client
             */
            bool sendData(const std::string &message);

            /**
             * @brief Receive loop is running.
             */
            bool isRunning() const;

            /**
             * @brief Get client information.
             * @retval {ip}:{port}
             */
            std::string getClientInfo() const;

            /**
             * @brief Define message handler operate function.
             * @note  Perform the main operation in this function (FPGA control & Fault processing).
             * @param handler call back function pointer.
             */
            void setMessageHandler(SessionMessageHandler handler);
        
        private:
            void receiveLoop();
            std::string DefaultMessageProcess(const std::string& message);

            int client_fd;
            struct sockaddr_in client_addr;
            bool running;
            SessionMessageHandler messageHandler;
    };

    bool SocketSendData(int fd, const char *buf, const uint64_t &sendLength, ssize_t *origin_ret = nullptr);
    bool SocketRecvData(int fd, char* buf, const uint64_t &recvLength, ssize_t *origin_ret, uint64_t *recvBytes);
}

#endif
