#ifndef LINUX_SESSION_H
#define LINUX_SESSION_H

#include <string>
#include <memory>
#include <functional>
#include <thread>
#include <unistd.h>
#include <errno.h>
#include <iostream>
#include <cstring>
#include <atomic>
#ifdef __linux__
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#endif
#include "system_tools/aligned_buffer.h"
#include "server/socket_io_manager.h"

namespace vuprs
{
    /**
     * @brief use: void(int client_fd, const struct sockaddr_in& client_addr, const std::string& message)
     *
     * @param client_fd file descripter of client.
     * @param client_addr client information struct.
     * @param message message(command) to deal with.
     */
    using SessionMessageHandler = std::function<void(std::weak_ptr<vuprs::SocketIOManager> manager, const std::string &message)>;

    class LinuxSession
    {
    private:
        std::weak_ptr<vuprs::SocketIOManager> socketIOManager;

        std::atomic<bool> running;
        mutable std::mutex mut;

        std::atomic<bool> isIOManagerBind;

        std::string frameHeader, frameTailer; /* Frame Header & Tailer */

        vuprs::SessionMessageHandler messageHandler;

        void ReceiveLoop();

        std::string DefaultMessageProcess(const std::string &message);

    public:
        /**
         * @brief Generated by accept()
         */
        LinuxSession(const std::string &frameHeader, const std::string &frameTailer);
        ~LinuxSession();

        /* Disable copy */

        LinuxSession(const LinuxSession &) = delete;
        LinuxSession &operator=(const LinuxSession &) = delete;

        LinuxSession(LinuxSession &&other) = delete;
        LinuxSession &operator=(LinuxSession &&other) = delete;

        /**
         * @brief Start receive loop.
         */
        void Start();

        /**
         * @brief Close client file descriptor and stop running.
         */
        void Stop();

        /**
         * @brief Send string message to client
         */
        bool SendMessage(const std::string &message);

        /**
         * @brief Receive message.
         */
        void ReceiveMessage(const std::string &tailer, vuprs::SocketReceiveData *data);

        std::string ClientInformation() const;

        /**
         * @brief Receive loop is running.
         */
        bool IsRun() const;

        bool BindIOManager(std::shared_ptr<vuprs::SocketIOManager> ioManager);

        void UnbindIOManager();

        /**
         * @brief Define message handler operate function.
         * @note  Perform the main operation in this function (FPGA control & Fault processing).
         * @param handler call back function pointer.
         */
        void SetMessageHandler(vuprs::SessionMessageHandler handler);
    };
}

#endif
